//! Markdown report writer.
//!
//! Sentinel and Guardian both consume `Vec<Finding>` and present it differently
//! (CLI markdown, HTML dashboard, SOC 2 evidence export). This module ships
//! the canonical markdown form so the CLI example and any consumer that just
//! wants "render this to markdown" can share one implementation.

use crate::finding::{Finding, Severity};

const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Render a list of findings as a markdown report. The `target` is shown in the
/// title; `now_iso` is a pre-formatted timestamp (callers control the clock so
/// this stays deterministic for tests).
pub fn render_markdown(target: &str, findings: &[Finding], now_iso: &str) -> String {
    let mut by = std::collections::BTreeMap::<Severity, Vec<&Finding>>::new();
    for f in findings {
        by.entry(f.severity).or_default().push(f);
    }

    let count = |s: Severity| by.get(&s).map(|v| v.len()).unwrap_or(0);

    let score = (10i32
        - 4 * count(Severity::Critical) as i32
        - 2 * count(Severity::High) as i32
        - 1 * count(Severity::Medium) as i32)
        .max(0);

    let mut out = String::with_capacity(8 * 1024);
    out.push_str(&format!("# Audit Report — {target}\n\n"));
    out.push_str(&format!(
        "_Generated by Lictor Core v{VERSION} on {now_iso}_\n\n"
    ));
    out.push_str("---\n\n");
    out.push_str("## Summary\n\n");
    out.push_str(&format!("**Security score: {score}/10**  \n\n"));
    out.push_str("| Severity | Count |\n|---|---|\n");
    for s in [
        Severity::Critical,
        Severity::High,
        Severity::Medium,
        Severity::Low,
        Severity::Info,
    ] {
        out.push_str(&format!("| {} | {} |\n", pill(s), count(s)));
    }
    out.push_str("\n---\n\n");

    if findings.is_empty() {
        out.push_str(
            "No findings. The toolkit ran but didn't detect any of the 5 common AI-app failure \
             modes. That's a good sign — but it doesn't mean the app is secure. The toolkit is \
             a first pass, not a complete audit.\n",
        );
    } else {
        // Iterate severities in decreasing severity order.
        for s in [
            Severity::Critical,
            Severity::High,
            Severity::Medium,
            Severity::Low,
            Severity::Info,
        ] {
            let Some(items) = by.get(&s) else { continue };
            if items.is_empty() {
                continue;
            }
            out.push_str(&format!(
                "## {} — {} finding(s)\n\n",
                pill(s),
                items.len()
            ));
            for (i, f) in items.iter().enumerate() {
                out.push_str(&format!("### {}. {}\n\n", i + 1, f.title));
                out.push_str(&format!("**Category:** {}  \n", category_label(f.category)));
                if !f.where_found.is_empty() {
                    out.push_str(&format!("**Where:** `{}`  \n\n", f.where_found));
                } else {
                    out.push_str("\n");
                }
                out.push_str(&format!("{}\n\n", f.detail));
                if !f.remediation.is_empty() {
                    out.push_str(&format!("**How to fix:**  \n{}\n\n", f.remediation));
                }
                out.push_str("---\n\n");
            }
        }
    }

    out.push_str("\n## What this audit checked\n\n");
    out.push_str("This pass covers 5 of the most common failure modes in AI-built / vibe-coded apps:\n\n");
    out.push_str("1. **Secrets exposure** — API keys, JWTs, and credentials in HTML/JS bundles or `.env` paths.\n");
    out.push_str("2. **Database exposure** — Supabase / Firebase / public APIs returning data without auth.\n");
    out.push_str("3. **Auth surface** — admin paths reachable without server-side gates.\n");
    out.push_str("4. **CORS posture** — credential-bearing endpoints with permissive Access-Control headers.\n");
    out.push_str("5. **AI-agent surface** — detected chat / agent widgets that warrant prompt-injection review.\n\n");
    out.push_str("**This is a first-pass audit, not a full pentest.** Want a hands-on audit ");
    out.push_str("from a 20-year cybersec engineer? [lictor.ai](https://lictor.ai)\n");

    out
}

fn pill(s: Severity) -> &'static str {
    match s {
        Severity::Critical => "🟥 CRITICAL",
        Severity::High => "🟧 HIGH",
        Severity::Medium => "🟨 MEDIUM",
        Severity::Low => "🟦 LOW",
        Severity::Info => "⬜ INFO",
    }
}

fn category_label(c: crate::finding::Category) -> &'static str {
    match c {
        crate::finding::Category::Secrets => "secrets",
        crate::finding::Category::Database => "database",
        crate::finding::Category::Auth => "auth",
        crate::finding::Category::Cors => "cors",
        crate::finding::Category::AiAgent => "ai-agent",
        crate::finding::Category::General => "general",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::finding::{Category, Finding};

    #[test]
    fn empty_report_renders_no_findings_message() {
        let s = render_markdown("https://x.test", &[], "2026-05-10 12:00");
        assert!(s.contains("No findings"));
        assert!(s.contains("Security score: 10/10"));
    }

    #[test]
    fn score_decrements_per_severity() {
        let findings = vec![
            Finding::new(Severity::Critical, Category::Secrets, "C"),
            Finding::new(Severity::High, Category::Auth, "H"),
            Finding::new(Severity::Medium, Category::Cors, "M"),
        ];
        let s = render_markdown("https://x.test", &findings, "2026-05-10 12:00");
        // 10 - 4 - 2 - 1 = 3
        assert!(s.contains("Security score: 3/10"), "{s}");
    }

    #[test]
    fn score_floors_at_zero() {
        let findings = vec![
            Finding::new(Severity::Critical, Category::Secrets, "C1"),
            Finding::new(Severity::Critical, Category::Secrets, "C2"),
            Finding::new(Severity::Critical, Category::Secrets, "C3"),
        ];
        let s = render_markdown("https://x.test", &findings, "2026-05-10 12:00");
        assert!(s.contains("Security score: 0/10"));
    }
}
